YumBaseError: safe str(e).  BZ 963698
PackageKit tries to log a YumBaseError instance with:

self.error(ERROR_MISSING_GPG_SIGNATURE, _to_unicode(e), exit=False)

However, _to_unicode() only converts utf8 strings to unicode,
and is a no-op for exception instances.  The logger module then
tries to convert e to str, and str(e) fails, since e.__str__()
returns unicode.  I think str(e) should not traceback.

test with:

>>> import yum.Errors
>>> e = yum.Errors.YumBaseError(u'ěšč')
>>> unicode(e) # worked already
u'\u011b\u0161\u010d'
>>> str(e) # this used to fail
'\xc4\x9b\xc5\xa1\xc4\x8d'