YumRepo.populate(): always decompresses new database
There's a race that has showed up in automated tests:

$ createrepo foo && createrepo bar # tiny repos
$ repoquery --repofrompath tmp,file://foo
OK..
$ repoquery --repofrompath tmp,file://bar
Error: Check uncompressed DB failed.

Here foo & bar happen to have the same timestamp, but different sizes.
Repoquery copies the new .bz2 file, but repo_gen_decompress() skips
decompression because old uncompressed file has the same timestamp.